"use client";

import { useState } from "react";
import { Map, Send, ChevronRight, Clock, BookOpen, Lock, CheckCircle2, Loader2 } from "lucide-react";

const sampleRoadmap = [
  {
    phase: "Phase 1 — Foundations",
    duration: "2 weeks",
    topics: [
      { title: "JavaScript Fundamentals", status: "done", est: "3 days" },
      { title: "ES6+ Features (Arrow, Destructuring, Spread)", status: "done", est: "2 days" },
      { title: "Async/Await & Promises", status: "in-progress", est: "3 days" },
      { title: "Module System (ESM/CJS)", status: "locked", est: "2 days" },
    ],
  },
  {
    phase: "Phase 2 — React Ecosystem",
    duration: "3 weeks",
    topics: [
      { title: "React Core (JSX, Components, Props)", status: "locked", est: "4 days" },
      { title: "Hooks: useState, useEffect, useContext", status: "locked", est: "4 days" },
      { title: "State Management (Zustand / Redux Toolkit)", status: "locked", est: "5 days" },
      { title: "React Router v6", status: "locked", est: "2 days" },
    ],
  },
  {
    phase: "Phase 3 — Advanced Patterns",
    duration: "2 weeks",
    topics: [
      { title: "Performance Optimization (memo, useMemo)", status: "locked", est: "3 days" },
      { title: "Testing (Vitest + React Testing Library)", status: "locked", est: "4 days" },
      { title: "Next.js App Router", status: "locked", est: "5 days" },
    ],
  },
];

export default function RoadmapPage() {
  const [skill, setSkill] = useState("");
  const [level, setLevel] = useState("beginner");
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(true);

  const handleGenerate = () => {
    setLoading(true);
    setTimeout(() => { setLoading(false); setGenerated(true); }, 1800);
  };

  const statusIcon = (s: string) => {
    if (s === "done") return <CheckCircle2 size={14} className="text-green-400" />;
    if (s === "in-progress") return <div className="w-3.5 h-3.5 rounded-full border-2 border-aura-primary border-t-transparent animate-spin" />;
    return <Lock size={14} className="text-aura-muted" />;
  };

  return (
    <div className="space-y-8 max-w-6xl mx-auto">
      <div>
        <h1 className="text-3xl font-black text-aura-text flex items-center gap-3">
          <Map className="text-aura-primary" size={28} /> Learning Roadmap
        </h1>
        <p className="text-aura-muted mt-1 text-sm">AI-generated personalized learning paths via AWS Bedrock.</p>
      </div>

      {/* Generator */}
      <div className="card p-6 space-y-4">
        <h2 className="font-semibold text-aura-text">Generate a New Roadmap</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="md:col-span-2">
            <input
              className="input"
              placeholder="What do you want to learn? (e.g. React.js, Machine Learning, AWS)"
              value={skill}
              onChange={(e) => setSkill(e.target.value)}
            />
          </div>
          <select className="input" value={level} onChange={(e) => setLevel(e.target.value)}>
            <option value="beginner">Beginner</option>
            <option value="intermediate">Intermediate</option>
            <option value="advanced">Advanced</option>
          </select>
        </div>
        <button onClick={handleGenerate} disabled={loading} className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed">
          {loading ? <><Loader2 size={16} className="animate-spin" /> Generating with Bedrock...</> : <><Send size={15} /> Generate Roadmap</>}
        </button>
      </div>

      {/* Active roadmap */}
      {generated && (
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="font-bold text-aura-text text-lg">React.js Mastery Path</h2>
              <p className="text-xs text-aura-muted mt-0.5">Generated by Claude 3 Sonnet · 7 weeks · 17 topics</p>
            </div>
            <div className="flex items-center gap-4">
              <div className="text-right">
                <div className="text-xs text-aura-muted">Progress</div>
                <div className="text-sm font-bold text-aura-text">2 / 17</div>
              </div>
              <div className="w-16 h-16 rounded-full relative flex items-center justify-center"
                style={{ background: "conic-gradient(#7c6af7 42deg, #1e2130 0deg)" }}>
                <div className="absolute inset-2 rounded-full bg-aura-card flex items-center justify-center">
                  <span className="text-xs font-bold text-aura-primary">12%</span>
                </div>
              </div>
            </div>
          </div>

          {sampleRoadmap.map((phase) => (
            <div key={phase.phase} className="card p-6 space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="font-bold text-aura-text">{phase.phase}</h3>
                <div className="flex items-center gap-1 text-xs text-aura-muted">
                  <Clock size={12} /> {phase.duration}
                </div>
              </div>
              <div className="space-y-2">
                {phase.topics.map((topic) => (
                  <div key={topic.title}
                    className={`flex items-center gap-3 p-3 rounded-xl border transition-colors ${
                      topic.status === "done"
                        ? "bg-green-500/5 border-green-500/20"
                        : topic.status === "in-progress"
                        ? "bg-aura-primary/5 border-aura-primary/20"
                        : "bg-aura-border/20 border-aura-border/50 opacity-60"
                    }`}>
                    {statusIcon(topic.status)}
                    <span className={`flex-1 text-sm font-medium ${
                      topic.status === "locked" ? "text-aura-muted" : "text-aura-text"
                    }`}>{topic.title}</span>
                    <div className="flex items-center gap-1 text-xs text-aura-muted">
                      <BookOpen size={11} /> {topic.est}
                    </div>
                    {topic.status !== "locked" && (
                      <ChevronRight size={14} className="text-aura-muted" />
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
