AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: StuddyBuddy AI — AWS-native serverless backend

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        DYNAMODB_TABLE_PREFIX: !Ref TablePrefix
        BEDROCK_MODEL_ID: !Ref BedrockModelId
        BEDROCK_REGION: !Ref AWS::Region
        JUDGE0_API_URL: !Ref Judge0ApiUrl
        JUDGE0_API_KEY: !Ref Judge0ApiKey
        JUDGE0_API_HOST: !Ref Judge0ApiHost
        S3_BUCKET_NAME: !Ref LogsBucket
        FRONTEND_URL: !Ref FrontendUrl
        NODE_ENV: production
    Tracing: Active
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date'"
      AllowOrigin: !Sub "'${FrontendUrl}'"

Parameters:
  TablePrefix:
    Type: String
    Default: studdybuddy
    Description: Prefix for all DynamoDB table names
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: AWS Bedrock model ID
  Judge0ApiUrl:
    Type: String
    Default: https://judge0-ce.p.rapidapi.com
    Description: Judge0 API base URL
  Judge0ApiKey:
    Type: String
    NoEcho: true
    Description: RapidAPI key for Judge0
  Judge0ApiHost:
    Type: String
    Default: judge0-ce.p.rapidapi.com
    Description: Judge0 RapidAPI host header
  FrontendUrl:
    Type: String
    Default: '*'
    Description: Amplify frontend URL for CORS (e.g. https://myapp.amplifyapp.com)

# ============================================================
# Lambda Functions
# ============================================================
Resources:

  GenerateRoadmapFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${TablePrefix}-generateRoadmap
      Handler: functions/generateRoadmap.lambdaHandler
      CodeUri: dist/
      Description: Generate personalized learning roadmap using Bedrock AI
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RoadmapsTable
        - S3WritePolicy:
            BucketName: !Ref LogsBucket
        - Statement:
          - Effect: Allow
            Action: bedrock:InvokeModel
            Resource: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-sonnet-*
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /api/roadmap/generate
            Method: POST

  SimplifyConceptFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${TablePrefix}-simplifyConcept
      Handler: functions/simplifyConcept.lambdaHandler
      CodeUri: dist/
      Description: Simplify programming concepts using Bedrock (proficiency-adaptive)
      Policies:
        - Statement:
          - Effect: Allow
            Action: bedrock:InvokeModel
            Resource: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-sonnet-*
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /api/concept/simplify
            Method: POST

  GenerateQuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${TablePrefix}-generateQuiz
      Handler: functions/generateQuiz.lambdaHandler
      CodeUri: dist/
      Description: Generate adaptive quiz questions using Bedrock
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref QuizzesTable
        - Statement:
          - Effect: Allow
            Action: bedrock:InvokeModel
            Resource: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-sonnet-*
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /api/quiz/generate
            Method: POST

  AnalyzeCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${TablePrefix}-analyzeCode
      Handler: functions/analyzeCode.lambdaHandler
      CodeUri: dist/
      Description: Execute code via Judge0, explain via Bedrock, log to DynamoDB
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CodeLogsTable
        - S3WritePolicy:
            BucketName: !Ref LogsBucket
        - Statement:
          - Effect: Allow
            Action: bedrock:InvokeModel
            Resource: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-sonnet-*
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /api/code/analyze
            Method: POST

  EvaluateSolutionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${TablePrefix}-evaluateSolution
      Handler: functions/evaluateSolution.lambdaHandler
      CodeUri: dist/
      Description: Evaluate exercises via Judge0 + Bedrock, update XP and proficiency
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref QuizzesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProficiencyTable
        - Statement:
          - Effect: Allow
            Action: bedrock:InvokeModel
            Resource: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-sonnet-*
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /api/solution/evaluate
            Method: POST

  UpdateXPFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${TablePrefix}-updateXP
      Handler: functions/updateXP.lambdaHandler
      CodeUri: dist/
      Description: Update user XP, level, streak, and badge data
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref XPHistoryTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /api/xp/update
            Method: POST

  GetScheduledReviewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${TablePrefix}-getScheduledReviews
      Handler: functions/getScheduledReviews.lambdaHandler
      CodeUri: dist/
      Description: Retrieve due and upcoming spaced-repetition reviews
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ReviewsTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /api/reviews/{userId}
            Method: GET

  GetUserProgressFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${TablePrefix}-getUserProgress
      Handler: functions/getUserProgress.lambdaHandler
      CodeUri: dist/
      Description: Retrieve comprehensive user progress, proficiency, and knowledge gaps
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
        - DynamoDBReadPolicy:
            TableName: !Ref ProficiencyTable
        - DynamoDBReadPolicy:
            TableName: !Ref RoadmapsTable
        - DynamoDBReadPolicy:
            TableName: !Ref XPHistoryTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /api/progress/{userId}
            Method: GET

# ============================================================
# DynamoDB Tables
# ============================================================

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true

  RoadmapsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}-roadmaps
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  QuizzesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}-quizzes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  ProficiencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}-proficiency
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  ReviewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}-reviews
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: scheduledFor
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ScheduledFor-index
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: scheduledFor
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true

  CodeLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}-codelogs
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true

  XPHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}-xphistory
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  ConceptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}-concepts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

# ============================================================
# S3 Bucket (Logs / Backups)
# ============================================================

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${TablePrefix}-logs-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90

# ============================================================
# Outputs
# ============================================================

Outputs:
  ApiEndpoint:
    Description: API Gateway base URL
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
    Export:
      Name: !Sub ${TablePrefix}-ApiEndpoint

  UsersTableName:
    Value: !Ref UsersTable
    Export:
      Name: !Sub ${TablePrefix}-UsersTable

  LogsBucketName:
    Value: !Ref LogsBucket
    Export:
      Name: !Sub ${TablePrefix}-LogsBucket
